language: node_js

node_js:
  - 10.15.3

cache: yarn

jobs:
  include:
    - stage: dry-run-release
      if: branch != master
      script:
        - yarn release:dryRun
    - stage: release
      deploy:
        provider: script
        on:
          branch: master
        skip_cleanup: true
        script:
          - yarn release
